# Autopilot Haproxy demo
#
# For most use cases, it's better to build a custom image using this Haproxy base image

haproxy:
    image: dekobon/haproxy
    restart: always
    mem_limit: 512m
    env_file: _env
    environment:
        - BACKEND=example
        - CONSUL_AGENT=1
        - ACME_ENV=staging
    ports:
        - 80
        - 443
        - 9090 # so we can see telemetry
    labels:
        - triton.cns.services=haproxy

example:
    image: autopilotpattern/nginx-example-app
    mem_limit: 128m
    env_file: _env
    environment:
        - CONSUL_AGENT=1
    expose:
        - 4000 # not strictly necessary because we don't link
    restart: always
    labels:
        - triton.cns.services=example

# Start with a single host which will bootstrap the cluster.
# In production we'll want to use an HA cluster.
consul:
    image: consul:v0.7.0
    restart: always
    mem_limit: 128m
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    ports:
      - 8500
    dns:
       - 127.0.0.1
    labels:
        - triton.cns.services=consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
